### ISSUE TITLE
Rewrite the meal planner project using .NET 7 and C# 11

### ISSUE THREAD

**Issue by dan-koller** [dan-koller/meal-planner#3]
# Idea

Since this is a basic but also very good project to learn about database connections and entity models in a language, I decided to rewrite this app using .NET 7 and C#.

# TODOs

- [ ] Create the database and tables in SQLite and/or SQL Server
- [ ] Create the entity models as `classlib`???
- [ ] Create the DataContext and DataContextExtensions as `classlib`??
- [ ] Add an `xunit` project for unit testing and check if the db connection can be established
- [ ] Create a `console` app and rewrite the core functionality to it
- [ ] **Maybe** Add a `web` project to this using razor pages
